### ISSUE TITLE
Games deleting on Game Install Sync

### ISSUE THREAD

**Issue by joenuts690** [CosmicScale/PSBBN-Definitive-English-Patch#16]
Any way to prevent this or remedy this? I tend to take out the SSD a couple times overtime and install new games as I go.

**Comment by joenuts690** [comment]
Basically speaking, I want a way to disable the sync with the "Games" folder where you place the games you want to install.

**Comment by CosmicScale** [comment]
That is just how the game installer works. It synchronises the games from the folders on your PC to the PS2 drive. If you remove games from the `games` folder on your PC, they are also removed from the PS2 drive. If you add games to the `games` folder on your PC, they are added to the PS2 drive.

I know the current game sync method may not be ideal for everyone. I plan to implement a more flexible solution in the future. 

If the problem is a lack of HDD space on your PC, then there is a workaround for now:
1. Rename all your game files so their filenames start with the Game ID, then sync them.
2. Replace the game files on your PC with zero-size files that have identical names.
3. Add more games to the 'games' folder, then re-sync.
