### ISSUE TITLE
PS2HDMI Fix for PS2 HDMI dongles

### ISSUE THREAD

**Issue by NewProject64** [CosmicScale/PSBBN-Definitive-English-Patch#32]
I have a cheap PS2 to HDMI dongle to connect my console to a computer screen (AOC FHD / 144mhz) and every time I launch a PS1 game disc, usually at some point I lose the image (during cut scenes or when I start a race on GT2 for example) and the only way I got it to work fine without my screen blinking all the time and lose the image was by using DKWDRV. So I was wondering: does PSBBN have a feature/way to fix this HDMI issue? Because every time I start a PS1 game on PSBBN, after the playstation logo, the screen turns off due to no HDMI signal. To play a PS1 game on PSBBN Iam always forced to use a TV with a SCART interface.

Ive used DKWDRV only to fix this HDMI issue, so I could play my original PS1 games so I dont know what this tool really is or its capable or if there is other ways to fix my problem.

**Comment by CosmicScale** [comment]
DKWDRV does not support internal drives. PSBBN uses POPStarter and the POPS emulator for PS1 games. The fix is far beyond the scope of this project but I've got two suggestions:
1. [Look at the POPStarter documentation](https://bitbucket.org/ShaolinAssassin/popstarter-documentation-stuff/wiki/index). Special Cheats can be enabled to force 480p.
2. Continue to use DKWDRV as you were before.

If you need any more help with this then Google is your friend :)
